spring.application.name=wordcraft
server.port=8080
spring.jpa.show-sql=true
cloud.aws.region.static=ap-southeast-2
cloud.aws.s3.bucket=wordcraft-uploads-jkm

# H2 Console (개발용 — prod 배포 시 제거 또는 false로 변경)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
